### ISSUE TITLE
View Post Details [3]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-flying_circus#23]
Given a user is looking at a list of posts
When they click on the post title
Then they should be directed to the post detail page
And the details should include:

- [x] Title
- [x] Author's name
- [x] Category
- [x] Publication date
- [x] Content

**Comment by chesney-hardin** [comment]
**SERVERSIDE**

- [ ] Define query to join tables with all details for each post
- [ ] Define get request based on single post
