### ISSUE TITLE
View All Posts [3]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-flying_circus#24]
Given the user clicks on the "Posts" link in the navbar
When they are directed to the /posts page
Then they should see a list of all posts, with the post title, author name, and category
And the posts should be ordered by the date they were added, most recent first

**Comment by chesney-hardin** [comment]
**SERVERSIDE**

- [ ] Create table of posts with specified properties
- [ ] Populate it with posts in sql database
- [ ] Create posts.py file in views
- [ ] Define GET requests for posts
