### ISSUE TITLE
Add a comment to a post [given well rested, then 2 (probably 3, though)]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-flying_circus#6]
Given a user is viewing the post details or a post's comments
When they click the "Add Comment" button
Then they should be routed to a comment form
And once the form is submitted
Then they should be routed to the comment page for that post

**Comment by chesney-hardin** [comment]
_Question for client_
-Do you want the post that is being commented on to be displayed at the top?
-If yes, which post details should be displayed?
